import { Page } from '@playwright/test';

/**
 * Shared base class for Page Objects generated by the "Submit New Request"
 * pipeline (tests/<suite>/page-objects/*.page.ts). Each such suite targets an
 * arbitrary, externally-submitted application URL rather than this repo's own
 * OpenCart storefront/admin -- unlike src/pages/storefront/BasePage's
 * `gotoRoute`, there is no fixed route convention to build in here, so each
 * page object supplies its own absolute URL to `open()`.
 */
export abstract class BasePage {
  constructor(public readonly page: Page) {}

  async open(url: string): Promise<void> {
    await this.page.goto(url);
  }
}
